"""Build pre-rendered terminal mascot frames from PNG assets."""
from __future__ import annotations

from pathlib import Path
from pprint import pformat

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "hund" / "assets" / "mascot"
TARGET = ROOT / "hund" / "ui" / "mascot_frames.py"
TINTS = {"bone": "#E3E3E4", "nord": "#D8DEE9", "synthwave": "#F28FAD"}


def _sprite_frames(path: Path) -> list[Image.Image]:
    """Split a grid sprite sheet into non-empty 16x16 cells, row-major."""
    image = Image.open(path).convert("RGBA")
    if image.width % 16 or image.height % 16:
        raise ValueError(f"sprite sheet dimensions must be multiples of 16: {path}")
    frames: list[Image.Image] = []
    for y in range(0, image.height, 16):
        for x in range(0, image.width, 16):
            frame = image.crop((x, y, x + 16, y + 16))
            if frame.getchannel("A").getbbox() is not None:
                frames.append(frame)
    if not frames:
        raise ValueError(f"sprite sheet contains no visible frames: {path}")
    return frames


def _half_blocks(image: Image.Image) -> str:
    pixels = image.load()
    lines: list[str] = []
    for y in range(0, 16, 2):
        line = []
        for x in range(16):
            top = pixels[x, y][3] >= 48
            bottom = pixels[x, y + 1][3] >= 48
            line.append("█" if top and bottom else "▀" if top else "▄" if bottom else " ")
        lines.append("".join(line).rstrip())
    return "\n".join(lines)


def build() -> None:
    poses = {
        "sitting": _sprite_frames(ASSETS / "Dog_Sit_Idle.png"),
        "standing": _sprite_frames(ASSETS / "Dog_Stand_Idle.png"),
        "playful": _sprite_frames(ASSETS / "Dog_Pose_Idle.png"),
        "running": _sprite_frames(ASSETS / "Dog_Run.png"),
    }
    rendered = {
        skin: {state: tuple(_half_blocks(frame) for frame in frames) for state, frames in poses.items()}
        for skin in TINTS
    }
    source = (
        '"""Generated by scripts/build_mascot_frames.py; no Pillow at runtime."""\n\n'
        f"TINTS = {pformat(TINTS, sort_dicts=True)}\n\n"
        f"FRAMES = {pformat(rendered, sort_dicts=True, width=100)}\n"
    )
    TARGET.write_text(source, encoding="utf-8")


if __name__ == "__main__":
    build()
